### PR TITLE
Make await QuerySingle consistent whether or not use values/values list

### PR DESCRIPTION
**Pull request by elisong**
Make await QuerySingle consistent whether or not use values/values list

## Description

- change returns (**may not backward compatible**)

  -  await  `.get().values()` or `.get_or_none().values()` or `.first().values()`  return dict (if db execute result not None)
  -  await  `.get().values_list()` or `.get_or_none().values_list()` or `.first().values_list()`  return tuple.
  - await  `.get().values_list(flat=True)` or `.get_or_none(flat=True).values_list()` or `.first().values_list(flat=True)`  return just scalar.

- add exceptions `DoesNotExist` and `MultipleObjectsReturned` for `.get().values()` and `.get().values_list()`.

## Motivation and Context

Let's compare `.filter()` to `.get()` in exists code:

- `Model.filter()` returns queryset, if be awaited, return list of model objects.
- `Model.get()` returns "querysingle", if be awaited, return one model object.

Next compare `.filter().values()` to `.get().values()`

- `Model.filter().values()` returns valuesquery, if be awaited, return list of dicts.
- `Model.get().values()` returns valuesquery, if be awaited,return list of one dict. **should be return only one dict** ?

In addition, if object does not exist, `Model.get()` will raise `tortoise.exceptions.DoesNotExist`. if multiple objects returned, `Model.get()` will raise `tortoise.exceptions.MultipleObjectsReturned`. **Both exceptions lost when use** `Model.get().values()` .

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by long2ice — APPROVED** [review]

**Comment by long2ice** [comment]
Which is a breaking change, I'm not sure whether we need to do like that.

**Comment by elisong** [comment]
return type for await `.get().values()`. before this PR, It returns with list of dict, while this PR change it to just dict.

**Comment by elisong** [comment]
It truly affect people who have used '.get().values()` every often, deserve fully discuss before merged.

**Comment by long2ice** [comment]
That's right

**Comment by Masynchin** [comment]
Cool feature, something like `(data,) = data` or `data = data[0]` looks enough to do break changes

**Comment by Masynchin** [comment]
@long2ice any plans to merge? Maybe it can be in 0.18?

**Comment by long2ice** [comment]
I decide to merge it, could you resolve conflicts?

**Review by long2ice — APPROVED** [review]

**Comment by Masynchin** [comment]
> I decide to merge it, could you resolve conflicts?

Will try after school 👍🏻

**Comment by Masynchin** [comment]
@long2ice I have fixed conflicts, but have not access to @elisong branch. I created fork of this branch and sent PR with fixed commits. Elisong seemed to be out of GH for month, so I can create direct PR from [fixed fork](https://github.com/Masynchin/tortoise-orm/tree/make-await-QuerySingle-consistent-whether-or-not-use-values/values_list)

**Comment by long2ice** [comment]
OK

**Review by long2ice — APPROVED** [review]

**Pull request merged**
