### PR TITLE
A unified, robust and bug-free connection management interface for the ORM

### PR DESCRIPTION
**Pull request by blazing-gig**
## Description
This PR provides for a much more robust implementation of the connection management interface of the ORM which is primarily geared towards improving performance and usability.

## Motivation and Context
I was really excited that a native asyncIO based ORM was in town and implemented a lot of API constructs similar to the Django ORM since I personally like the way queries are expressed in Django. When I was tinkering around,
- The first thing I noticed was that connections to the DB were being established on boot-up which I wasn't very comfortable with. 
- The second thing I noticed, after tinkering around with the source code, was that though the docs said that `Tortoise.get_connection` returns a connection for a given DB alias, there was another construct named `current_transaction_map` and another method named `get_connection` in `tortoise/transactions.py` that was being used internally for storing and retrieving connections.

This PR tries to address the above problems/inconsistencies as follows:

- A unified connection management interface for accessing, modifying and deleting connections using `asyncio` native constructs.
- Lazy connection creation i.e the underlying connection to the DB gets established only upon execution of a query.
- Fixes a lot of bugs that could occur due to connections being stored in two different places ( `Tortoise._connections` and `current_transaction_map`). Also, the usage of ContextVars has been done in the most optimal way.

## How Has This Been Tested?
- All test cases present currently pass for all environments. Once the design and solution are agreed upon, I could write tests for the newly added code.
- Any code attempting to access a specific connection using an alias has now been refactored to use the new connections interface (including all existing tests)

Once the solution has been accepted and reviewed by the core team, I can update the tests, docs and changlog accordingly.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added the changelog accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by abondar** [comment]
Hi!

Thank you for your PR

Could you provide motivation for this piece?
> Lazy connection creation i.e the underlying connection to the DB gets established only upon execution of a query.

When I was designing this one on the start I did that so that tortoise could fail fast, and user of orm would know that something gone wrong from the start

With lazy connection that could be delayed into future, which could bring more confusion

**Comment by blazing-gig** [comment]
Hey @abondar 

Thanks for responding quickly. While I do agree to your point (failing fast), I see the following concerns which might take higher precedence over this:

- When used in a web framework, If multiple databases are present, lets say 5 and each had a pool size of 5, then the server would have to wait until all 25 connections are established depending on the connection pool implementation. This could become a bottleneck as it increases boot-time for services (especially when auto-scaled). The goal is to keep the boot-time to a minimum.
- If the DB connection for some reason couldn't be established, it would only affect the routes which contain DB interactions. There could be other routes which don't interact with the DB at all. So instead of the entire service failing(DoS), only part of it would fail which can be detected and fixed quite easily. (A variant of the fail fast in some sense)
- If most routes of a web server don't interact with the DB at all, then delaying connection creation just creates better availability of resources until the point it's created. 

Let me know your thoughts on the same.

**Comment by blazing-gig** [comment]
Hey @abondar , is there any update on this or are we blocked somewhere ? Any concerns ?

**Comment by blazing-gig** [comment]
Hey @abondar , any thoughts/updates on this ? I'd really like this to get merged so that I'd be able to use the ORM in both my personal as well as professional python projects.

**Comment by blazing-gig** [comment]
@long2ice @abondar Is the project still being actively maintained? If yes, how do I create more traction around this PR to take things forward? Any help from the team would be greatly appreciated. Thanks.

**Review by abondar — APPROVED** [review]
Hi!

PR seems to be legit to me

Sorry for slow responses, even though project is being maintained, it is done on available free time basis, which could be quite limited at times

@long2ice could you please prepare release for this PR?

**Comment by long2ice** [comment]
Thanks for your contribution! @abondar I will spend some time to review it. Which is a big change and break some api, I have some concerns about that and considering whether we need to accept these changes. And also please see https://github.com/tortoise/tortoise-orm/pull/1001/checks?check_run_id=4581321590 to make that pass.

**Review by long2ice — APPROVED** [review]

**Comment by blazing-gig** [comment]
Hey @abondar @long2ice , thanks for the response. I do understand that most of the work done is during free time. Its just that I found myself some time to work on this and thought that it would be great if merged quickly so that I could recommend using the ORM at my workplace for a few projects. 

Personally, from the research I've done, I feel that this project has an edge over other async ORMs' out there in the market with respect to feature set, performance and ease-of-use (especially for Django buffs). Hoping to become a long term contributor in the near future. 

Also, @long2ice I've made sure that all APIs' that currently exist for fetching DB connections have been made backward compatible with the new design and so this wouldn't cause breaking changes off the bat. These APIs' can be marked as deprecated and probably removed in a future release. Let me know your thoughts.

**Comment by blazing-gig** [comment]
Hey @abondar @long2ice , I've rebased my branch with the latest changes from develop. I've written unit tests and added docs for the new connection interface as well.

I'd like to urge either of you to review these changes at the earliest and prepare a release for the same as it would become very difficult for me to keep rebasing this branch with changes from develop as there would be more than a few conflicts and refactoring that I'd have to do again and again.

**Comment by blazing-gig** [comment]
@abondar @long2ice Also, I have no idea why the codacy check is failing bcoz I've run pydocstyle on my machine and it doesn't complain about this. Let me knw if this is a bug in codacy or whether I'm missing something.

**Comment by blazing-gig** [comment]
Hey @abondar @long2ice , since the changes have already been reviewed and accepted, I request you to kindly merge this ASAP and prepare a release.

**Comment by blazing-gig** [comment]
Hey @abondar @long2ice checking in to see if there's any progress. Thanks.

**Comment by blazing-gig** [comment]
Hey @abondar @long2ice @grigi checking in to see if there's any progress. Thanks.

**Comment by blazing-gig** [comment]
Hey @abondar @long2ice @grigi checking in to see if there's any progress. Thanks.

**Comment by blazing-gig** [comment]
Hey @long2ice checking in to see if there's any progress. Thanks.

**Comment by blazing-gig** [comment]
Hey @long2ice checking in to see if there's any progress. Thanks.

**Comment by blazing-gig** [comment]
@long2ice Any update on this ?

**Comment by blazing-gig** [comment]
@abondar @long2ice Would like to know if this project is still being maintained. Thanks.

**Review by long2ice — APPROVED** [review]

**Comment by blazing-gig** [comment]
@long2ice The particular test which is failing in the pipeline for py3.8 / py3.9 is **passing** on my local machine. Would like to knw the version of MySQL being using in the CI env for testing. Any further ideas in debugging the issue would be greatly helpful.

**Comment by long2ice** [comment]
The mysql is github actions builtin

**Comment by blazing-gig** [comment]
@long2ice I'm unable to run tests with MySQL 5.7 on my local machine. There seem to be a lot of problems around [this issue](https://dba.stackexchange.com/questions/48704/mysql-5-6-datetime-incorrect-datetime-value-2013-08-25t1700000000-with-er) in particular. Tables aren't getting created properly. Tried changing sql_mode as well but to no effect.

Finally had to remove the `tzinfo=pytz.utc` kwarg from `tests.testmodels.DefaultModel` to get the tests to run. But there were a couple of tests which failed but they were bcoz of the tz issue again. Not really sure how to proceed further with debugging this issue as I'm unable to reproduce the CI issue on my local machine. Any suggestions/help would be greatly appreciated.

**Comment by blazing-gig** [comment]
@long2ice Any suggestions around how to move forward with this ?

**Comment by long2ice** [comment]
Did you merged develop? Which ci is passed

**Comment by long2ice** [comment]
And you should add changelog about this PR

**Comment by blazing-gig** [comment]
> And you should add changelog about this PR

Sure. Will do.

**Comment by blazing-gig** [comment]
> Did you merged develop? Which ci is passed

Yup. Could you please trigger the pipeline ? Also, if possible, could you give access for triggering pipelines so that I might be able to debug it at will thereby helping to quicken the process

**Comment by blazing-gig** [comment]
@long2ice The pipeline still hasn't been triggered. Could you please do it ?

**Comment by blazing-gig** [comment]
@long2ice Any idea on why the codacy check is failing ? pep257 and pydocstyle checks on my local machine are passing.

**Comment by blazing-gig** [comment]
@long2ice As I mentioned earlier, all tests are passing on my local machine. Any help around why this specific test is failing in the CI pipeline would be greatly appreciated as I'm unable to proceed with the debugging effort and is stalling the PR from getting merged.

**Comment by long2ice** [comment]
I fixed it in develop, you can merge it first

**Comment by blazing-gig** [comment]
> I fixed it in develop, you can merge it first

@long2ice I've merged it. Could you pls trigger the pipeline ?

**Comment by long2ice** [comment]
OK, just need update the changelog

**Comment by long2ice** [comment]
Please resolve conflicting files, thanks!

**Comment by blazing-gig** [comment]
@long2ice Sure will do. Also, could you tell me whether SemVer practises are being followed for versioning ? If not, I'm assuming that the next version would be `0.18.2` under which I'd be adding the Changelog

**Comment by long2ice** [comment]
Just add in 0.18.2

**Review by long2ice — APPROVED** [review]

**Comment by blazing-gig** [comment]
@long2ice I've fixed all breaking tests from my end. Also, I've removed the custom `ConnectionPoolWrapper` implementation in the psycopg client class as I felt it was unnecessary and was complicating things. Feel free to drop in ur suggestions if any.

**Comment by blazing-gig** [comment]
@long2ice Also, please trigger the pipeline again

**Review by long2ice — APPROVED** [review]

**Comment by long2ice** [comment]
Looks great! Just need add the changelog

**Comment by blazing-gig** [comment]
@long2ice Hey, I've updated the changelog as well. Please do have a look at it. I think it can be merged now. Let me knw if there's anything else that needs to be done. Thanks 🙂

**Comment by blazing-gig** [comment]
@long2ice Hey I think test_bulk_create_mix_specified test is failing since the resulting list from the queryset is not sorted but assertListSortEqual is expecting it to be sorted... Could you please fix this from ur end ?

**Comment by blazing-gig** [comment]
@long2ice Also this is similar to the bulk issue which was fixed earlier I believe

**Comment by blazing-gig** [comment]
@long2ice Either you could add an `order_by` clause on the query or refactor the test to just check for existence.

**Review by long2ice — APPROVED** [review]

**Comment by long2ice** [comment]
What about merge develop first?

**Comment by blazing-gig** [comment]
@long2ice 

```py
async def test_bulk_create_mix_specified(self):
    await UniqueName.bulk_create(
        [UniqueName(id=id_) for id_ in range(10000, 11000)]
        + [UniqueName() for _ in range(1000)]
    )
    
    all_ = await UniqueName.all().values("id", "name") # --> This is gonna return results in a random order
    self.assertEqual(len(all_), 2000)
    
    self.assertListSortEqual(
        all_[:1000], [{"id": id_, "name": None} for id_ in range(10000, 11000)], sorted_key="id"
    ) # --> This expectation is gonna fail
    inc = all_[1000]["id"]
    self.assertListSortEqual(
        all_[1000:], [{"id": val + inc, "name": None} for val in range(1000)], sorted_key="id"
    )
```

The bottomline is that sometimes the test passes and sometimes it fails becoz of the inconsistency I've highlighted above...
Would you be able to fix this ?

**Comment by long2ice** [comment]
strange, ci of develop is right

**Comment by blazing-gig** [comment]
> strange, ci of develop is right

@long2ice Not really sure but from what I observed the tests seem to pass sometimes and fail during others. Nevertheless could you pls check the specific concern I've highlighted above? What's your take on it?

**Comment by blazing-gig** [comment]
@long2ice Also, I'd suggest triggering the pipeline again... If it succeeds then it could be a one off inconsistency which we could potentially ignore. If not, it has to be dealt with. Either which way, triggering the pipeline again could add some clarity to the matter.

**Comment by blazing-gig** [comment]
@long2ice I guess my observation is true. Since the pipeline is passing, I believe we can proceed to merge it and then probably look into the inconsistency issue. If not, I believe the merge is getting unnecessarily delayed... Let me knw ur thoughts

**Comment by long2ice** [comment]
OK, I merge it. Thanks!

**Comment by blazing-gig** [comment]
@long2ice thanks! Also, do you plan on creating a separate issue for the inconsistency which I've mentioned above? If so, let me knw. Would be happy to contribute there as well... Also would be looking to solve other issues related to connection management and related behavior.

**Pull request merged**
