### PR TITLE
Make `DateField` accept valid date str and add `QuerySet.select_for_update()`.

### PR DESCRIPTION
**Pull request by long2ice**
## Description

- Make `DateField` accept valid date str.
- Add `QuerySet.select_for_update()`.
## Motivation and Context

And the `QuerySet.select_for_update()` need `pypika` latest master branch because it's not publish `select_for_update` support to pypi now.
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by long2ice** [comment]
What's the ci problem?

**Comment by long2ice** [comment]
can pass ci after next release of `pypika` with https://github.com/kayak/pypika/pull/477

**Review by grigi — COMMENTED** [review]
:+1:

**Comment by grigi** [comment]
Seems like `for update` is not supported on sqlite, and pypika correctly doesn't emit it.
Could manage this behaviour using the capabilities framework in Tortoise.
I think trying to emulate this is not necessary, Just adding some documentation stating that it's a no-op for SQLite? And skip testing on SQLite.

**Comment by long2ice** [comment]
I'm happy to do that, but don't know when pypika next release...

**Comment by grigi** [comment]
I see.

We can wait a while. PyPika has relatively often releases.

**Comment by long2ice** [comment]
@grigi Could this accept merge?

**Pull request merged**
