### PR TITLE
[WIP] Allow filter to aggregate function

### PR DESCRIPTION
**Pull request by lntuition**
Allow `Q` for filter of aggregate Functions.

Fixed : #309 

* [x] Allow _filter param to aggregate
* [x] Add testcase
* [ ] Update Changelog

### CODE REVIEW

**Comment by lntuition** [comment]
I Found current solution. but It's not beautiful. I think join to Pypika object sometimes use `_get_joins_for_related_field` and sometimes do not use. I really make confusing. If we can, choosing one solution is more better. looks like current Q object is too oriented only filter option in queryset

**Comment by grigi** [comment]
I see what you mean. Agreed. `Q` is very filter oriented, and now the functions code has a lot of similarities with it. And behaviour isn't entierly consistent.

How do you think we should resolve this? Should we mark it as technical debt with big `# TODO:` statements (as in get to it later, preferably once we have an eagle's eye view) or try and fix it up-front. Note that we have to be careful with breaking backwards compatibility. (Although I think this is an implementation detail, it's not going to have a large fallout)

**Comment by lntuition** [comment]
Ah... I think we have big debt.. we should devide into small units.. and do hard refactor of that.. We need to prune many code. As you said, with pruning can break backwards compatibility. Also marking TODO can be good, too..

**Comment by grigi** [comment]
I vote to put TODOs now, and possibly treat it as a larger project. E.g. like fixing up Fields that was the driver between 0.14 and 0.15

**Comment by lntuition** [comment]
And does `Q` works different with database? I think it works sqlite good. but not working with postgres

**Comment by grigi** [comment]
> And does `Q` works different with database? I think it works sqlite good. but not working with postgres

It should work everywhere... I mean we run the entire test suite for each DB?

**Comment by lntuition** [comment]
hmm... i need to check why ci failed. maybe my testcase is wrong?

**Comment by lntuition** [comment]
I found what i wrong. but i need to think more to support this feature. I left this PR to WIP for a while

**Pull request closed without merging**
