### PR TITLE
add test for accessing a query

### PR DESCRIPTION
**Pull request by spacemanspiff2007**
This is the first attempt to reproduce issue #780 with a test case

### CODE REVIEW

**Comment by spacemanspiff2007** [comment]
@long2ice 
I have a mistake in the test case
```python
self.assertEqual(await query.all(), [team_2])
```
should be
```python
self.assertEqual(await query.all(), [event_2])
```
but all the tests are green.
Is the testcase not executed in ci?

**Comment by long2ice** [comment]
What's the result in local?

**Comment by spacemanspiff2007** [comment]
I can't run the test locally since I am on a windows machine and the instructions in the readme won't work.
But here I start the query:
```python
query = Event.filter(pk__in=sub_query_team_1) 
```
and you see it should yield an Event instance, not a Team instance since I filter on the Events.
So this should definitely fail:
```python
self.assertEqual(await query.all(), [team_2])
```

**Comment by long2ice** [comment]
Try merge develop first

**Comment by spacemanspiff2007** [comment]
> Try merge develop first

I'm sorry I don't understand. Should I merge the PR into the Tortoise branch "develop"?
Should I merge the Tortoise branch "develop" into my branch and rebase?

**Comment by long2ice** [comment]
Yes, rebase develop to your develop branch

**Comment by spacemanspiff2007** [comment]
Like this?

**Comment by spacemanspiff2007** [comment]
@long2ice 
After pulling the latest develop changes locally I could run the tests locally, too.
That helped a lot. Thank you!

The test now fails as expected since the query changes which it should not (bug).
This is good to be merged.

**Review by long2ice — APPROVED** [review]

**Comment by spacemanspiff2007** [comment]
@long2ice do I still have to do something so this can get merged?

**Comment by long2ice** [comment]
Yes, just make ci pass

**Comment by spacemanspiff2007** [comment]
> Yes, just make ci pass

It won't pass because it's a bug in tortoise-orm and I don't know how to fix the bug.
This just adds a test case so someone else with more knowledge can fix it.
See issue #780 for details.

**Comment by spacemanspiff2007** [comment]
Can we get this merged?

**Comment by spacemanspiff2007** [comment]
@long2ice : I added some comments - could you merge this?

**Review by long2ice — APPROVED** [review]

**Comment by spacemanspiff2007** [comment]
@abondar 
Could you merge this please?

**Pull request closed without merging**
