### PR TITLE
Add missing example

### PR DESCRIPTION
**Pull request by beucismis**
## Description

Add promised example after `related_name` argument description in the documentation.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by long2ice** [comment]
Thanks!

**Comment by beucismis** [comment]
@long2ice, can I add myself to contributors?

**Comment by long2ice** [comment]
All contributors  could be found there https://github.com/tortoise/tortoise-orm/graphs/contributors easy, that file may be not necessary

**Comment by beucismis** [comment]
Right.

**Pull request merged**
