### PR TITLE
add info about generated to models doc and it's interaction with pk

### PR DESCRIPTION
**Pull request by AEnterprise**
## Description
make people aware of the implications of marking an IntField as pk

## Motivation and Context
see #214 

## How Has This Been Tested?
just a doc change, nothing functional

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by AEnterprise** [comment]
also noticed the contribution guidelines have some weird formatting, probably sphix instead of markdown, should i make a seperate PR for that, add it into this one or let you take care of that?
image

**Comment by grigi** [comment]
Yes, all docs are supposed to be Sphinx-extended ReStructuredText, and not Markdown. Because that allows us to mix and match generated and manual docs quite nicely. 

What is the issue with the Contribution Guide formatting? It should be viewed as part of the docs: https://tortoise-orm.readthedocs.io/en/latest/CONTRIBUTING.html
(Note I'm asking because I have seen it so much that any papercuts are not apparent to me anymore.

**Comment by AEnterprise** [comment]
for the contributing guidelines github links to them as https://github.com/tortoise/tortoise-orm/blob/develop/docs/CONTRIBUTING.rst in the sidepannel (and even with a small popup if it's your first PR) and it looks like the image i showed above in there

**Comment by grigi** [comment]
Ah, so we use the wrong link in the PR template. Ok, I'll fix that.
Thanks for pointing it out.

**Comment by grigi** [comment]
Yes, I can't find any way to change it. Does GH want me to create a special page that just have links to the docs or something?

**Comment by AEnterprise** [comment]
i think github just wants it to be a markdown file

**Comment by grigi** [comment]
No, that's not it. I just doesn't support directives. Anyways, I'll merge this PR and have a look at splitting the document up in some way.

**Pull request merged**
