### PR TITLE
feat: support pydantic2.0

### PR DESCRIPTION
**Pull request by long2ice**
## Description

Support pydantic2.0
## Motivation and Context

https://github.com/tortoise/tortoise-orm/discussions/1419
## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added the changelog accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PeiPeiWow** [comment]
Hi, I am using  pydantic2.0, but still have this error, please help!
from app.models import AnyUser, Token, User_Pydantic, Token_Pydantic, UserIn_Pydantic
  File "/Users/qilong/Desktop/fastApiUser/app/models.py", line 34, in <module>
    User_Pydantic = pydantic_model_creator(AnyUser, name="AnyUser")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qilong/Desktop/fastApiUser/venv/lib/python3.11/site-packages/tortoise/contrib/pydantic/creator.py", line 437, in pydantic_model_creator
    model = cast(Type[PydanticModel], type(_name, (PydanticModel,), properties))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qilong/Desktop/fastApiUser/venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 95, in __new__
    private_attributes = inspect_namespace(
                         ^^^^^^^^^^^^^^^^^^
  File "/Users/qilong/Desktop/fastApiUser/venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 287, in inspect_namespace
    and value.__module__ == namespace['__module__']
                            ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '__module__'

**Comment by PeiPeiWow** [comment]
> Did you use latest code?

Yes, I used the latest code.
Maybe you have any other ideas?

**Comment by PeiPeiWow** [comment]
When I downgraded pydantic==2.0.0, I got this
255324618-57bae3c9-2f77-44b1-bf6f-20b64ff65079


_ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastapi 0.100.0 requires pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4, but you have pydantic 2.0 which is incompatible._

so I have to install pydantic==1.10.11, and this solves the problem.

Do you have any other ideas?

**Comment by farzbood** [comment]
**FastAPI (0.100.0)** dependency list shows that it excluded Pydantic (2.0.0, 2.0.1) so first of all using the latest stable version of both frameworks would be a rational choice, which in case of **Pydantic** it is **(2.0.3)**
While the maintaners of TortoiseORM are working on finalizing the version bump to support **Pydantic V2** ,for clarification of conflicts, you can refer to the list of breaking changes with corresponding migration guides, based on Pydantic official docs.

[https://docs.pydantic.dev/latest/migration/#migration-guide](url)
Good Luck

**Comment by PeiPeiWow** [comment]
> **FastAPI (0.100.0)** dependency list shows that it excluded Pydantic (2.0.0, 2.0.1) so first of all using the latest stable version of both frameworks would be a rational choice, which in case of **Pydantic** it is **(2.0.3)** While the maintaners of TortoiseORM are working on finalizing the version bump to support **Pydantic V2** ,for clarification of conflicts, you can refer to the list of breaking changes with corresponding migration guides, based on Pydantic official docs.
> 
> [https://docs.pydantic.dev/latest/migration/#migration-guide](url) Good Luck

### Thank you so much

**Pull request merged**
