### PR TITLE
Add Case-When support

### PR DESCRIPTION
**Pull request by elisong**
Add Case-When support

## Description

Use  `Case(When(condition1,..., conditionN, then=...), When(...), default=...)` for building classic `CASE WHEN ... THEN ... ELSE ... END` sql snippet.

-  **condition** can be Q object or keyword filter,   like input in `Model.filter()`, `Model.exclude()`

## Motivation and Context

Using "CASE-WHEN-ELSE-END" sql snippet to derive new field is a common practice. This PR makes it more convenient/readable to achieve it than using `RawSQL`.

## How Has This Been Tested?

Please refer to test cases in `tests.test_case_when.py` for instance.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added the changelog accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by long2ice** [comment]
What aboue move them to `expressions.py`? I think they are not functions. Btw, please resolve conflicts.

**Comment by elisong** [comment]
Agree, I have tried that. But if place it in `expressions.py`, it cause Circular (or cyclic) imports (`functions.py` <-> `expressions.py`).

Can it be considered as 'Generic' function ?

**Comment by long2ice** [comment]
OK...Can then have same parent class? Or subclass of `Function`?

**Comment by elisong** [comment]
「the former expects When instance., but the latter expects field: Union[str, F, ArithmeticExpression, "Function"] as first argument.」 If `When` inherits from 'Function', it seems not a problem......

**Comment by long2ice** [comment]
That's real a problem, in django, they are all expressions

**Comment by elisong** [comment]
Done

**Pull request merged**
