### PR TITLE
Create integration function for blacksheep

### PR DESCRIPTION
**Pull request by rozumalex**
## Description
Adds function for quick integration with [BlackSheep framework](https://github.com/Neoteroi/BlackSheep)

## Motivation and Context
According to the dashboards ([TechEmpower](https://www.techempower.com/benchmarks/) & [klen.github.io](http://klen.github.io/py-frameworks-bench/)) it seems to be the fastest python web framework.

## How Has This Been Tested?
I've implemented an example app and tested that integration works correctly.

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by long2ice — APPROVED** [review]

**Comment by long2ice** [comment]
Hello, you can run `make style ci` local to make ci pass

**Comment by rozumalex** [comment]
> Hello, you can run `make style ci` local to make ci pass

Thank you for tip!

> Hello, you can run `make style ci` local to make ci pass

Hello! Thank you for the tip.

The bandit is passing locally:
Screenshot 2021-08-16 at 15 17 23

But several tests are failed both on develop and this branches:
Screenshot 2021-08-16 at 15 17 43

Can you imagine what is the reason for that?

**Comment by long2ice** [comment]
See https://github.com/tortoise/tortoise-orm/pull/865/checks?check_run_id=3340410786, looks like also failed

**Comment by rozumalex** [comment]
Should be fine now

Screenshot 2021-08-18 at 21 00 59

**Review by long2ice — APPROVED** [review]

**Comment by long2ice** [comment]
Great! Thanks for your contribution!

**Pull request merged**
