### PR TITLE
Fix IntegrityError with unique field and get_or_create

### LINKED ISSUE #140: IntegrityError with unique field and get_or_create
**Describe the bug**
Hi!
First of all thank you for developing such useful ORM.
I am not sure that this is really bug, maybe I am doing something wrong.
I get IntegrityError with fields having unique=True and using get_or_create.

**To Reproduce**
Models.py is:

    class CheckDates(Model):
        id = fields.IntField(pk=True)
        check_date = fields.DateField(unique=True)

        def __str__(self):
            return self.check_date.strftime('%Y-%m-%d')

    class Projects(Model):
        id = fields.IntField(pk=True)
        name = fields.CharField(max_length=255, unique=True)

        def __str__(self):
            return self.name

    class Results(Model):
        id = fields.IntField(pk=True)
        date = fields.ForeignKeyField('models.CheckDates', related_name='results')
        project = fields.ForeignKeyField('models.Projects', related_name='results')
        suspicious_url = fields.CharField(max_length=255)

        class Meta:
            unique_together = ('date', 'project', 'suspicious_url')

        def __str__(self):
            return self.suspicious_url

I have file for generating schemas:

    from tortoise import Tortoise, run_async

    async def init(generate=False):
        await Tortoise.init(
            db_url='sqlite://db.sqlite3',
            modules={'models': ['AntiDoorway.models']}
        )
        if generate:
            await generate_schemas()

    async def generate_schemas():
        await Tortoise.generate_schemas()

    async def close_conns():
        await Tortoise.close_connections()

    if __name__ == '__main__':
        run_async(init(generate=True))

And file with main pipeline (some code is excluded as irrelevant):
    
    def check_by_visiting(urls_dict: dict, project_name: str, check_date: date, counter_id: int) -> None:
        tasks = []
        loop = asyncio.get_event_loop()
        loop.run_until_complete(init())
        for url in urls_dict.keys():
            for platform in platforms:
                tasks.append(loop.create_task(main(url, project_name, check_date, counter_id, platform)))
        loop.run_until_complete(asyncio.wait(tasks))
        loop.run_until_complete(close_conns())
        loop.close()

    async def main(url: str, project_name: str, check_date: date, counter_id: int, platform: str) -> None:
        result = []
        try:
            date_id = await CheckDates.get_or_create(check_date=check_date)
        except exceptions.IntegrityError:
            date_id = await CheckDates.filter(check_date=check_date)
        date_id = date_id[0]
        project_id = await Projects.get_or_create(name=project_name)
        project_id = project_id[0]

        params = await form_request_params(platform)
        formed_url = await form_url(url)
        async with aiohttp.ClientSession() as session:
            try:
                response = await fetch_data(formed_url, params, session)
            except Exception as e:
                response = ''
        result.append(await check_counter_presence(response, counter_id))
        result.append(await return_reload_in_header(response))
        if any(result):
            try:
                await Results.get_or_create(date=date_id, project=project_id, suspicious_url=url)
            except (sqlite3.IntegrityError, exceptions.IntegrityError):
                pass

I get following errors when I run script with empty DB:
sqlite3.IntegrityError: UNIQUE constraint failed: checkdates.check_date
and
sqlite3.IntegrityError: UNIQUE constraint failed: results.date_id, results.project_id, results.suspicious_url
but all data is saved (well, I hope it is).
And no errors if date is already in DB.

**Expected behavior**
No error messages.

**Additional context**
So this might be a bug if I'm doing it right.

### PR DESCRIPTION
**Pull request by grigi**
Fixes #140

Had to introduce an extra lock for nested transactions for DB's that support it to prevent network errors with both PostgreSQL & MySQL.

### CODE REVIEW

**Comment by grigi** [comment]
@abondar based this on your original attempt to fix this. Please review.

**Comment by grigi** [comment]
Wow, Py3.6 gets so confused with contexts :sob: 
I feel we may just have to remove it from CI altogether...
It has been deprecated for a few months now...

Unfortunately it would mean dropping pypy too.

I'll just conditionally skip the test for now.

**Comment by grigi** [comment]
Another option is to disable all connection pooling on py3.6?

**Comment by AEnterprise** [comment]
wow didn't expect pooling to be such a major pain on 3.6

but personally i'm more in favor for dropping only specific features like pooling then dropping an entire version (prob best to log a warning on startup though so people are aware)

**Comment by grigi** [comment]
Py3.6 uses a contextvar backport, and unfortunately it has shortcomings. py3.7+ has extra state in their asyncio C-structs to keep track better.
I'm busy seeing what would be the lowest-impact change for disabling pooling for py3.6. It seems forcing a pool of 1 doesn't do it.
I suspect I would have to use explicit locking like I do for SQLite to get it working right.

**Comment by AEnterprise** [comment]
i think forcing a shared lock instead of making new locks for concurrent operations should do the trick

that and forcing a poolsize of 1 regardless since it can't use multiple so there is no reason to have any extras open

**Comment by grigi** [comment]
Well, in the meantime I'm getting hillarious errors, like "cannot rollback; the transaction is not yet started" but investigating further the cause is the dreaded "cannot perform operation: another operation is in progress".

And fixing race conditions fixes that.

**Comment by grigi** [comment]
@AEnterprise We are discussing the potential deprecation for py3.6 in #303
This PR fixes a bug, and should go in soon.
I'll merge this to master instead of develop, and cherry-pick the windows fix as well and release that. All the new feature work is going in as v0.16

**Comment by grigi** [comment]
I'll cherry pick the commits instead.

**Pull request merged**
