### PR TITLE
make JSONField accept valid json str value

### PR DESCRIPTION
**Pull request by long2ice**
## Description

make JSONField accept valid json str value
## Motivation and Context

resolve https://github.com/tortoise/tortoise-orm/issues/377
## How Has This Been Tested?

add test cases
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by grigi** [comment]
I don't think this is going to fix the root issue in #377 
The issue is that JSONB is a native JSON support, and because JSON is any of `str, int, float, bool, None, list, dict` a `str` is a valid option. Reading it back is correct, just the update is doing it wrong.

Thanks for your attempt, but I don't feel comfortable having intentional type-morphing as a feature (where we would normally try and avoid such behaviour).

**Comment by long2ice** [comment]
Is it not a good choice to update ``JSONField`` with json str value? Maybe we need it like ``CharEnumField`` or ``IntEnumField``,in db it's always ``Text``.

**Comment by grigi** [comment]
For SQLite and MySQL, yes. But not for PostgreSQL. It's of type `JSONB` there. So an actual JSON blob.

I did quick look, and the issue is that passing as a reference it expects a JSON string, but a read returns a JSON blob.
When passing it as part of the SQL then it expects JSON content, but not quoted as a string.

Tortoise fixes this by automatically parsing the JSON (because it expects it to be a string) but that still populates the data with incorrect data.

**Comment by grigi** [comment]
e.g. when inserted via a `.save()` the value is read back as:
```py
{'some': ['text', 3]}
```
But after an `.update()` it's:
```py
'{"some": ["text", 3]}'
```

If anything we need to be consistent. This is a PostgreSQL specific bug.

**Comment by long2ice** [comment]
well,I'm not so familiar with PostgreSQL,so I close this pr?

**Comment by grigi** [comment]
Ok, I'll work on this issue.

**Pull request closed without merging**
