### PR TITLE
Improve code and fix typo

### PR DESCRIPTION
**Pull request by lntuition**
This is minor patch to improve code and fix typo. It is not urgent. So if you don't like often minor patchs, just open this PR. Then, i will add minor patch to this branch.

* [x] remove duplicate in relational
* [x] fix typo in function
* [x] update README

### CODE REVIEW

**Comment by grigi** [comment]
These kinds of TLC changes are welcome.
IF you feel it's a bit much, I can give you commit access. Then you can merge these small fixes in yourself?

**Comment by lntuition** [comment]
@grigi Also i am satisfied with current way. Get commit access should be more convenient. Thank you so much for always caring :smile:

**Comment by grigi** [comment]
@lntuition Did you get the commit-access invite? I sent it a day ago now?

**Comment by lntuition** [comment]
@grigi I didn't get commit-access email. Could you send it again?.. Or should you check email address?

**Comment by grigi** [comment]
@lntuition GH says it sent the invite to your profile's email, or go to: https://github.com/tortoise/tortoise-orm/invitations directly?

**Comment by lntuition** [comment]
@grigi I'm now accept your invite with url. Thank you so much :+1:

**Comment by grigi** [comment]
A pleasure :smile:

Not much really changes. Just note that when you merge a PR, please squash and make the git message sensible.

It defaults to just listing all the commit messages, which is quite messy. 
I often put a short summary similar to the readme, or some of the PR summary message.
If it can be described in one sentence, then you don't need anything else.

**Pull request merged**
