### PR TITLE
Fix documentation link for functions.

### PR DESCRIPTION
**Pull request by zoliszeredi**
## Description
Documentation link for aggregation is [broken](https://tortoise-orm.readthedocs.io/en/latest/examples/basic.html#aggregation). It refers to renamed file.

## Motivation and Context
- fixes docs to render functions examples

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by grigi** [comment]
Thank you :-)
Do you want commit access? You have been doing lots of detail oriented PR's.

**Comment by zoliszeredi** [comment]
I'd like that. I could do more documentation PRs.

**Comment by grigi** [comment]
You have an invite :-)

**Comment by grigi** [comment]
Please try to merge your own PR?

**Pull request merged**
