### PR TITLE
WIP: add partitions to create table

### PR DESCRIPTION
**Pull request by evstratbg**
this pr adds PARTITION BY statement to psql and mysql

### CODE REVIEW

**Comment by evstratbg** [comment]
In order to finish that, creation of pk should be disabled. Is it ok?

**Comment by cofin** [comment]
This feature would be great to see.  What needs to be completed so this PR can be merged?  I'm not able to see the details on the tests above.

**Comment by long2ice** [comment]
Yes, we need make all test pass

**Comment by waketzheng** [comment]
Thanks for the effort! 🍰
Close as long time no update, feel free to reopen.

**Pull request closed without merging**
