### PR TITLE
Add Codspeed performance benchmarks

### PR DESCRIPTION
**Pull request by henadzit**
## Description
- Add [Codspeed](https://codspeed.io/) GitHub Action
- Add a few benchmarks based on https://github.com/tortoise/orm-benchmarks for creation, getting and filtering

## Motivation and Context
Codspeed should help us tracking performance regression and improvement. It lets you see the time difference introduced by commits but also see how long each method or function takes. I'm planning to do some performance related work soon, so it should be helpful. Codspeed is used by other large open-source projects, for instance, [pydantic](https://codspeed.io/pydantic/pydantic).

Here's a report example https://codspeed.io/henadzit/tortoise-orm/branches/feat%2Fcodspeed, although it lacks the comparison with the baseline because, well, there is no baseline yet. It should start appearing after this PR is merged. This example is from [PR in my fork](https://github.com/henadzit/tortoise-orm/pull/1).

Here's an example of `Model.get` profiling (we can already see that 20% of time is spent in pypika which is crazy):
Screenshot 2024-12-29 at 08 54 19

## How Has This Been Tested?
`make ci`
`pytest tests/benchmarks --codspeed`

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added the changelog accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by henadzit** [comment]
@abondar could you please add the repo to https://codspeed.io/? Here's [the guide](https://docs.codspeed.io/integrations/providers/github).

**Comment by henadzit** [comment]
@abondar could you please add the repo to https://codspeed.io/? Here's [the guide](https://docs.codspeed.io/integrations/providers/github). I don't seem to have enough permissions. Lack of the `CODSPEED_TOKEN` secret is the reason why the Codspeed check is failing right now.

**Comment by abondar** [comment]
@henadzit I am not sure how to proceed with it - I added repository to list of repos in codespeed, but the moment it should have shown me popup with token to copy - popup immediately appeared and disappeared and  I didn't have a chance to note down the token. 

But it doesn't allow me to resetup integration again, as it says "Disabling repository is not supported yet"

**Comment by henadzit** [comment]
> @henadzit I am not sure how to proceed with it - I added repository to list of repos in codespeed, but the moment it should have shown me popup with token to copy - popup immediately appeared and disappeared and I didn't have a chance to note down the token.
> 
> But it doesn't allow me to resetup integration again, as it says "Disabling repository is not supported yet"

You should be able to find the token in Settings. Here's how it looks in my fork:

Screenshot 2024-12-29 at 20 18 44

**Comment by abondar** [comment]
Seems like it works now

**Review by abondar — APPROVED** [review]

**Pull request merged**
