### PR TITLE
Fix serialization of Enum values with Pydantic

### LINKED ISSUE #576: Unable to serialise CharEnumField
**Describe the bug**
Inability to serialise a field of type `CharEnumField` due to ValidationError

**To Reproduce**
Example:
```python
## Lets say we have a Enum like such:
class ProfilePrivacyEnum(Enum):
	PRIVATE = "private"
	POSTS_ONLY = "posts_only"
	COMMENTS_ONLY = "comments_only"
	ALL_CONTENT = "all_content"

## And a model like such:
class Test(models.Model):
	privacy_setting = fields.CharEnumField(
		enum_type=ProfilePrivacyEnum,
		default="all_content"
	)

	def __str__(self) -> int:
		return self.pk

## with a PydanticModel defined using the contrib method "pydantic_model_creator" as such
Test_Pydantic = pydantic_model_creator(Test)

....
....

## and we then try to serialise a instance of this model with `from_tortoise_orm`:
test= await Test_Pydantic.from_tortoise_orm(test)
```

the following error occurs:
```
File "c:\program files\python38\lib\site-packages\pydantic\main.py", line 508, in from_orm
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for api_v1.models.Test.ptjsvp
privacy_setting
  str type expected (type=type_error.str)
```

**Expected behavior**
Am expecting it to not error. Instead, expecting the string representation of that Enum member.

**Additional context**
I am able to get around this by excluding the field using PydanticMeta, and instead using a computed attribute that that simply returns the value of the enum.

### PR DESCRIPTION
**Pull request by Hummer12007**
Fixes #576

Fixes serialization of Enum values by using their values.

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Hummer12007** [comment]
Bump

**Comment by long2ice** [comment]
Hi, is it real a bug? I try it but no errors.

**Comment by Hummer12007** [comment]
While the test cases passes without the change, I have some errors in my production code without the PR applied. I'll try reducing it to a minimal example.

**Comment by Hummer12007** [comment]
@long2ice Here is an example which crashes on master but works with this PR:
```
import asyncio
import logging
from enum import Enum

from tortoise import fields, Tortoise
from tortoise.models import Model
from tortoise.contrib.pydantic import pydantic_model_creator

DB_URL = 'sqlite://:memory:'

class FooType(Enum):
    A = "a"
    B = "b"
    C = "c"

class Foo(Model):
    name = fields.CharField(32, null=False)
    type = fields.data.CharEnumField(FooType, null=False, required=True)

    @classmethod
    def py(cls):
        return pydantic_model_creator(cls, name=cls.__name__)

async def db_init():
    await Tortoise.init(db_url=DB_URL, modules={'models': [__name__]})
    await Tortoise.generate_schemas()

async def main():
    await db_init()
    try:
        await Foo.create(name="test", type=FooType.A)
        fs = await Foo.all()
        print(fs)
        model = Foo.py()
        for f in fs:
            print(await model.from_tortoise_orm(f))
    finally:
        await Tortoise.close_connections()

if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by Hummer12007** [comment]
Aaaah, adding a type annotation will probably solve this!

**Comment by Hummer12007** [comment]
Got to
```
import asyncio
from enum import Enum

from pydantic import constr
from tortoise import fields, Tortoise
from tortoise.models import Model
from tortoise.contrib.pydantic import pydantic_model_creator


DB_URL = 'sqlite://:memory:'

class FooType(Enum):
    A = "a"
    B = "b"
    C = "c"

class Foo(Model):
    name = fields.CharField(32, null=False)
    type: FooType = fields.data.CharEnumField(FooType, null=False, required=True)

    @classmethod
    def py(cls):
        return pydantic_model_creator(cls, name=cls.__name__)

async def db_init():
    await Tortoise.init(db_url=DB_URL, modules={'models': [__name__]})
    await Tortoise.generate_schemas()

async def main():
    await db_init()
    try:
        await Foo.create(name="test", type=FooType.A)
        fs = await Foo.all()
        print(fs)
        model = Foo.py()
        for f in fs:
            print(await model.from_tortoise_orm(f))
    finally:
        await Tortoise.close_connections()

if __name__ == '__main__':
    asyncio.run(main())
```
so far.
```
fuji@antonovka /tmp $ python test.py 
[<Foo: 1>]
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "test.py", line 35, in main
    model = Foo.py()
  File "test.py", line 23, in py
    return pydantic_model_creator(cls, name=cls.__name__)
  File "/home/fuji/.local/lib/python3.7/site-packages/tortoise/contrib/pydantic/creator.py", line 405, in pydantic_model_creator
    model = cast(Type[PydanticModel], type(_name, (PydanticModel,), properties))
  File "pydantic/main.py", line 262, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 314, in pydantic.fields.ModelField.infer
  File "pydantic/schema.py", line 951, in pydantic.schema.get_annotation_from_field_info
ValueError: On field "type" the following field constraints are set but not enforced: max_length. 
For more details see https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints
```

**Comment by Hummer12007** [comment]
Doing `class FooType(str, Enum):` like in the testsuite worked.

**Comment by Hummer12007** [comment]
Closing, as I figured out how to solve the proble
Mentioning that enums for `CharEnumField`s need to be defined as `class FooType(str, Enum):` for everything to work in the docs would certainly be helpful though.

**Pull request closed without merging**
