### PR TITLE
Add `optional` parameter to `pydantic_model_creator`

### PR DESCRIPTION
**Pull request by Daste745**
## Description
This addition allows specifying optional model parameters without modifying the database schema.

## Motivation and Context
This is particularly useful when declaring models for updating or querying data. This was explained in more detail and with an example in #642 and requested in #571.
My use case is creating a PATCH endpoint which allows users to update their username, password, bio etc. For this I would need to write a new model by hand or do some tricks when declaring it, which I don't want to do

## How Has This Been Tested?
I tested this with my FastAPI application. I created separate Pydantic models for reading, creating and updating user data: 
The read-only model excludes the "password" field (for obvious reasons).
The create model excludes readonly fields.
The update model excludes readonly + makes "username", "mail" and "password" optional, which allows users to update single fields at a time.

I wrote two test cases which check the differences between a model with and without "optional" fields.

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Daste745** [comment]
I added a "User" test model and wrote two passing test cases.
Please let me know if there needs to be any more work done on this feature.

**Comment by AhmedSoli** [comment]
Do we have an update here?

**Comment by Daste745** [comment]
I believe this PR is ready for a merge, although I don't understand the conflict in `tests/testmodels.py`. I've been using these changes in one of my projects (not active at the moment) and have not seen any issues with it.

**Comment by GonerGenesis** [comment]
any news on this?

**Comment by long2ice** [comment]
OK, just need resolve the conflicts

**Comment by Daste745** [comment]
Sorry this took so long, I forgot about this PR. Everything should be merging now, although I can see errors in CI on my fork, which I'm not sure how to fix.
```
mypy tortoise/ examples/ tests/ conftest.py
tests/contrib/test_pydantic.py: note: In member "setUp" of class "TestPydanticUpdate":
tests/contrib/test_pydantic.py:1298: error: Return type
"Coroutine[Any, Any, None]" of "setUp" incompatible with return type "None" in
supertype "TestCase"
        async def setUp(self) -> None:
        ^
Found 1 error in 1 file (checked 220 source files)
```

**Comment by Daste745** [comment]
Mypy isn't throwing the error anymore, should be good to go. Tests are passing locally (tested with sqlite only).

**Comment by Daste745** [comment]
Hi @long2ice, could you please take a look at this? I think it would be a nice feature to have for some people.

**Review by long2ice — APPROVED** [review]

**Comment by long2ice** [comment]
Thanks!

**Pull request merged**
